# MySQL Settings
spring.datasource.url=jdbc:mysql://localhost:3306/fruity_fusion
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
# Security Settings
spring.security.user.name=admin
spring.security.user.password=password123

# --- MPESA CONFIGURATION ---
mpesa.consumer.key=0zRnVisXnOrxm2vIbiY6eNWrySGy4zK1UAS8kIytn8SkiCHb
mpesa.consumer.secret=IFlGVV1ssaaVKmVka1LBOan82kzX89D6cQkA5K3yRyB9NiKhZaUeZxugBxOOTAYA
mpesa.shortcode=174379
mpesa.passkey=bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919
mpesa.stkpush.url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
mpesa.auth.url=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
