# MySQL Settings
spring.datasource.url=jdbc:mysql://localhost:3306/fruity_fusion?serverTimezone=Africa/Nairobi
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Security Settings
spring.security.user.name=kelvin
spring.security.user.password=password123
# Google Gemini API Configuration
# 4. AI REPORTING (Gemini API)
# ==========================================
gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6JF4dFho0UpbnAJf_nyTs75vMFpB09TWq0-vrK15f8Iig}